apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-pod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-pod
  template:
    metadata:
      labels:
        app: people-pod
    spec:
      containers:
      - name: people
        image: people:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: people-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: people-pod
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30002
